In [105]:
import pandas as pd
import re

In [ ]:
import os

# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_brutos", "dados_colaboradores 1(DadosPrimarios).csv")

df = pd.read_csv(caminho_completo)

In [107]:
df['CPF'].head(10)

0       34512367890
1    024.878.550-22
2    123.456.789-00
3       78965432100
4       12345678900
5    987.654.321-00
6       00000000000
7       32165498700
8       78965412300
9       74185296300
Name: CPF, dtype: object

In [108]:
df.isnull().sum()

ID                         0
Nome                       0
Email                      5
CPF                        0
Data de Nascimento         0
Telefone                   0
Estado                     0
Cidade                     0
Endereço                   0
Formação Acadêmica         0
Treinamentos Realizados    0
dtype: int64

In [109]:
df['Email'] = df['Email'].fillna("Nao informado")

In [ ]:
df.rename(columns={'ID': 'idColaborador'}, inplace=True)

In [110]:
df.isnull().sum()

ID                         0
Nome                       0
Email                      0
CPF                        0
Data de Nascimento         0
Telefone                   0
Estado                     0
Cidade                     0
Endereço                   0
Formação Acadêmica         0
Treinamentos Realizados    0
dtype: int64

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       80 non-null     int64
 1   Nome                     80 non-null     object
 2   Email                    80 non-null     object
 3   CPF                      80 non-null     object
 4   Data de Nascimento       80 non-null     object
 5   Telefone                 80 non-null     object
 6   Estado                   80 non-null     object
 7   Cidade                   80 non-null     object
 8   Endereço                 80 non-null     object
 9   Formação Acadêmica       80 non-null     object
 10  Treinamentos Realizados  80 non-null     object
dtypes: int64(1), object(10)
memory usage: 7.0+ KB

In [112]:
df['Data de Nascimento'].head(10)

0    1992/05/09
1    1980-07-30
2    15-06-1999
3    1987-03-22
4    1990-12-01
5    01/03/1993
6    1985/07/30
7    14-02-1994
8    1987-05-09
9    1982-10-31
Name: Data de Nascimento, dtype: object

In [113]:
def limpar_e_converter(data):
    data = re.sub(r"[^0-9]+", "-", data)

    data = data.strip("-")

    return pd.to_datetime(data, dayfirst=True, errors="coerce")

df["Data de Nascimento"] = df["Data de Nascimento"].apply(limpar_e_converter)

df["Data de Nascimento"] = df["Data de Nascimento"].dt.strftime("%d-%m-%Y")

C:\Users\isabe\AppData\Local\Temp\ipykernel_12376\3533388452.py:6: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(data, dayfirst=True, errors="coerce")

In [114]:
df["Data de Nascimento"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 80 entries, 0 to 79
Series name: Data de Nascimento
Non-Null Count  Dtype
--------------  -----
80 non-null     object
dtypes: object(1)
memory usage: 772.0+ bytes

In [115]:
df["Data de Nascimento"] = pd.to_datetime(df["Data de Nascimento"], format="%d-%m-%Y",errors="coerce")

In [116]:
df["Data de Nascimento"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 80 entries, 0 to 79
Series name: Data de Nascimento
Non-Null Count  Dtype
--------------  -----
80 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 772.0 bytes

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       80 non-null     int64
 1   Nome                     80 non-null     object
 2   Email                    80 non-null     object
 3   CPF                      80 non-null     object
 4   Data de Nascimento       80 non-null     datetime64[ns]
 5   Telefone                 80 non-null     object
 6   Estado                   80 non-null     object
 7   Cidade                   80 non-null     object
 8   Endereço                 80 non-null     object
 9   Formação Acadêmica       80 non-null     object
 10  Treinamentos Realizados  80 non-null     object
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 7.0+ KB

In [118]:
df["Estado_Telefone"] = df["Telefone"].str.extract(r'(?:\(|-|\b)([A-Z]{2})(?:\)|\b)')

In [119]:
df.head(10)

,ID,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Cidade,Endereço,Formação Acadêmica,Treinamentos Realizados,Estado_Telefone
0,7,Sra. Vanessa Nogueira,vanessa.nogueira@exemplo,34512367890,1992-09-05,21 9876-1234 - RJ,RJ,Niterói,"Rua Mato Grosso, 192, Niterói - RJ",Ensino Médio Completo,"Excel Avançado, Segurança da Informação",RJ
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 11 93220-4567 - SP,SP,São Paulo,"Rua Rio Branco, 831, São Paulo - SP",Tecnólogo em Análise de Sistemas,Segurança da Informação,SP
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,(19) 99765-3332 - SP,SP,Santos,"Rua Horizonte Azul, 779, Santos - SP",Sistemas de Informação,Scrum Foundation,SP
3,10,Dr. Rafael Costa,rafael.costa@email.com,78965432100,1987-03-22,(71) 91234-5678 - BA,BA,Feira de Santana,"Rua Cruzeiro do Sul, 162, Feira de Santana - BA",Ensino Médio Completo,"Desenvolvimento Web com React, Excel Avançado,...",BA
4,11,Thiago Moura,thiago@dominio.com,12345678900,1990-01-12,(21) 99999-0001 - RJ,RJ,Niterói,"Rua do Sol, 121, Niterói - RJ",Engenharia de Software,"Desenvolvimento Web com React, Segurança da In...",RJ
5,12,Camila Andrade,camila.andrade,987.654.321-00,1993-03-01,(11)91234-5678 - SP,SP,Santos,"Rua Esperança, 999, Santos - SP",Engenharia de Software,Excel Avançado,SP
6,13,Bruno Oliveira,bruno@empresa,00000000000,1985-07-30,3199998888 - MG,MG,Contagem,"Rua Bela Vista, 648, Contagem - MG",Tecnólogo em Análise de Sistemas,"Desenvolvimento Web com React, Excel Avançado,...",MG
7,14,Ana Carolina,ana.carol@email.com,32165498700,1994-02-14,71988776655 - BA,BA,Feira de Santana,"Rua Acre, 555, Feira de Santana - BA",Tecnólogo em Análise de Sistemas,"Excel Avançado, Scrum Foundation",BA
8,15,Fernando Reis,fernando.reis@empresa.com.br,78965412300,1987-09-05,(85) 92345-6789 - CE,CE,Juazeiro do Norte,"Rua Bela Vista, 658, Juazeiro do Norte - CE",Tecnólogo em Análise de Sistemas,"Segurança da Informação, Excel Avançado, Curso...",CE
9,16,Isabela Monteiro,isabela.monteiro@gmail,74185296300,1982-10-31,(98) 99876-5432 - MA,MA,São Luís,"Rua Dom Pedro I, 997, São Luís - MA",Bacharelado em Ciência da Computação,Scrum Foundation,MA

In [ ]:

import sys
import os
# Adiciona o diretório-raiz do projeto ao sys.path
sys.path.append('/app')

import importlib
import utils.valida_telefone
importlib.reload(utils.valida_telefone)   # recarrega o módulo com as mudanças
from utils.valida_telefone import aplicar_validacao

# aplicando validação e formatação de telefone
df = aplicar_validacao(df, "Telefone", "Estado_Telefone")

df.head(20)

,ID,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Cidade,Endereço,Formação Acadêmica,Treinamentos Realizados,Estado_Telefone,telefone_limpo,estado_telefone,ddd_status,num_status,status_final
0,7,Sra. Vanessa Nogueira,vanessa.nogueira@exemplo,34512367890,1992-09-05,+55 (21) 9876-1234,RJ,Niterói,"Rua Mato Grosso, 192, Niterói - RJ",Ensino Médio Completo,"Excel Avançado, Segurança da Informação",RJ,2198761234,RJ,Válido,Inválido: celular com tamanho incorreto,Inválido: celular com tamanho incorreto
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 (11) 93220-4567,SP,São Paulo,"Rua Rio Branco, 831, São Paulo - SP",Tecnólogo em Análise de Sistemas,Segurança da Informação,SP,11932204567,SP,Válido,Válido,Válido
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,+55 (19) 99765-3332,SP,Santos,"Rua Horizonte Azul, 779, Santos - SP",Sistemas de Informação,Scrum Foundation,SP,19997653332,SP,Válido,Válido,Válido
3,10,Dr. Rafael Costa,rafael.costa@email.com,78965432100,1987-03-22,+55 (71) 91234-5678,BA,Feira de Santana,"Rua Cruzeiro do Sul, 162, Feira de Santana - BA",Ensino Médio Completo,"Desenvolvimento Web com React, Excel Avançado,...",BA,71912345678,BA,Válido,Válido,Válido
4,11,Thiago Moura,thiago@dominio.com,12345678900,1990-01-12,+55 (21) 99999-0001,RJ,Niterói,"Rua do Sol, 121, Niterói - RJ",Engenharia de Software,"Desenvolvimento Web com React, Segurança da In...",RJ,21999990001,RJ,Válido,Válido,Válido
5,12,Camila Andrade,camila.andrade,987.654.321-00,1993-03-01,+55 (11) 91234-5678,SP,Santos,"Rua Esperança, 999, Santos - SP",Engenharia de Software,Excel Avançado,SP,11912345678,SP,Válido,Válido,Válido
6,13,Bruno Oliveira,bruno@empresa,00000000000,1985-07-30,+55 (31) 9999-8888,MG,Contagem,"Rua Bela Vista, 648, Contagem - MG",Tecnólogo em Análise de Sistemas,"Desenvolvimento Web com React, Excel Avançado,...",MG,3199998888,MG,Válido,Inválido: celular com tamanho incorreto,Inválido: celular com tamanho incorreto
7,14,Ana Carolina,ana.carol@email.com,32165498700,1994-02-14,+55 (71) 98877-6655,BA,Feira de Santana,"Rua Acre, 555, Feira de Santana - BA",Tecnólogo em Análise de Sistemas,"Excel Avançado, Scrum Foundation",BA,71988776655,BA,Válido,Válido,Válido
8,15,Fernando Reis,fernando.reis@empresa.com.br,78965412300,1987-09-05,+55 (85) 92345-6789,CE,Juazeiro do Norte,"Rua Bela Vista, 658, Juazeiro do Norte - CE",Tecnólogo em Análise de Sistemas,"Segurança da Informação, Excel Avançado, Curso...",CE,85923456789,CE,Válido,Válido,Válido
9,16,Isabela Monteiro,isabela.monteiro@gmail,74185296300,1982-10-31,+55 (98) 99876-5432,MA,São Luís,"Rua Dom Pedro I, 997, São Luís - MA",Bacharelado em Ciência da Computação,Scrum Foundation,MA,98998765432,MA,Válido,Válido,Válido
10,17,Lucas Silva,lucas@lucas.com,111.222.333-44,1992-02-29,+55 (21) 98765-4321,RJ,Rio de Janeiro,"Rua Alvorada, 471, Rio de Janeiro - RJ",Tecnólogo em Análise de Sistemas,"Desenvolvimento Web com React, Scrum Foundatio...",RJ,21987654321,RJ,Válido,Válido,Válido
11,18,Tatiane Ramos,tatiane@ramos.com.br,987654321-00,1989-05-12,+55 (47) 99123-4567,SC,Florianópolis,"Rua da Saudade, 262, Florianópolis - SC",Sistemas de Informação,"Segurança da Informação, Scrum Foundation",SC,47991234567,SC,Válido,Válido,Válido
12,19,Pedro Henrique,pedro@henrique.com,456.789.123-00,1980-06-15,+55 (51) 99234-5678,RS,Caxias do Sul,"Rua do Sol, 696, Caxias do Sul - RS",Ensino Médio Completo,"Desenvolvimento Web com React, Scrum Foundation",RS,51992345678,RS,Válido,Válido,Válido
13,20,Juliana Duarte,juliana.duarte,15935745600,1996-03-03,+55 (41) 91234-5678,PR,Londrina,"Rua Dom Pedro I, 430, Londrina - PR",Engenharia de Software,"Excel Avançado, Desenvolvimento Web com React",PR,41912345678,PR,Válido,Válido,Válido
14,21,Carlos Alberto,carlos.alberto@email.com,45678912300,1984-08-15,+55 (65) 98765-4321,MT,Cuiabá,"Rua Primavera, 447, Cuiabá - MT",Bacharelado em Ciência da Computação,"Segurança da Informação, Excel Avançado",MT,65987654321,MT,Válido,Válido,Válido
15,22,Daniela Braga,daniela@braga.com,14725836900,1991-11-25,+55 (61) 99123-4567,DF,Brasília,"Rua Tocantins, 703, Brasília - DF",Bacharelado em Ciência da Computação,"Scrum Foundation, Desenvolvimento Web com Reac...",DF,61991234567,DF,Válido,Válido,Válido
16,23,Renato Lima,renato@lima,85296374100,1993-01-04,+55 (82) 99123-4567,AL,Maceió,"Rua Pernambuco, 984, Maceió - AL",Ensino Médio Completo,"Desenvolvimento Web com React, Segurança da In...",AL,82991234567,AL,Válido,Válido,Válido
17,24,Débora Costa,debora.costa@exemplo.com,369.258.147-00,1990-10-10,+55 (21) 99111-1222,RJ,Nova Iguaçu,"Rua da Saudade, 207, Nova Iguaçu - RJ",Tecnólogo em Análise de Sistemas,Curso de Power BI,RJ,21991111222,RJ,Válido,Válido,Válido
18,25,Anderson Melo,anderson@melo.org,123.456.789-99,1989-01-01,+55 (21) 99888-7766,RJ,Rio de Janeiro,"Rua da Saudade, 788, Rio de Janeiro - RJ",Tecnólogo em Análise de Sistemas,"Segurança da Informação, Scrum Foundation",RJ,21998887766,RJ,Válido,Válido,Válido
19,26,Beatriz Rocha,beatriz.rocha@webmail.com,74185296310,1995-06-06,+55 (31) 99123-4567,MG,Contagem,"Rua Amazonas, 342, Contagem - MG",Ensino Médio Completo,"Curso de Power BI, Desenvolvimento Web com Rea...",MG,31991234567,MG,Válido,Válido,Válido

In [121]:
df.head()

,ID,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Cidade,Endereço,Formação Acadêmica,Treinamentos Realizados,Estado_Telefone,telefone_limpo,estado_telefone,ddd_status,num_status,status_final
0,7,Sra. Vanessa Nogueira,vanessa.nogueira@exemplo,34512367890,1992-09-05,+55 (21) 9876-1234,RJ,Niterói,"Rua Mato Grosso, 192, Niterói - RJ",Ensino Médio Completo,"Excel Avançado, Segurança da Informação",RJ,2198761234,RJ,Válido,Inválido: celular com tamanho incorreto,Inválido: celular com tamanho incorreto
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 (11) 93220-4567,SP,São Paulo,"Rua Rio Branco, 831, São Paulo - SP",Tecnólogo em Análise de Sistemas,Segurança da Informação,SP,11932204567,SP,Válido,Válido,Válido
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,+55 (19) 99765-3332,SP,Santos,"Rua Horizonte Azul, 779, Santos - SP",Sistemas de Informação,Scrum Foundation,SP,19997653332,SP,Válido,Válido,Válido
3,10,Dr. Rafael Costa,rafael.costa@email.com,78965432100,1987-03-22,+55 (71) 91234-5678,BA,Feira de Santana,"Rua Cruzeiro do Sul, 162, Feira de Santana - BA",Ensino Médio Completo,"Desenvolvimento Web com React, Excel Avançado,...",BA,71912345678,BA,Válido,Válido,Válido
4,11,Thiago Moura,thiago@dominio.com,12345678900,1990-01-12,+55 (21) 99999-0001,RJ,Niterói,"Rua do Sol, 121, Niterói - RJ",Engenharia de Software,"Desenvolvimento Web com React, Segurança da In...",RJ,21999990001,RJ,Válido,Válido,Válido

In [122]:
df["ddd_status"].value_counts()

ddd_status
Válido                                         74
Inválido: DDD 81 não pertence ao estado RN      1
Inválido: DDD 84 não pertence ao estado MA      1
Inválido: DDD 41 não pertence ao estado RR      1
Inválido: DDD 41 não pertence ao estado TO      1
Inválido: DDD 11 não pertence ao estado BA      1
Inválido: DDD 11 não pertence ao estado nan     1
Name: count, dtype: int64

In [123]:
df["num_status"].value_counts()

num_status
Válido                                         71
Inválido: celular com tamanho incorreto         6
Inválido: fixo com dígito inicial incorreto     3
Name: count, dtype: int64

In [124]:
df["status_final"].value_counts()

status_final
Válido                                                                                      70
Inválido: celular com tamanho incorreto                                                      4
Inválido: DDD 81 não pertence ao estado RN e Inválido: celular com tamanho incorreto         1
Inválido: DDD 84 não pertence ao estado MA e Inválido: celular com tamanho incorreto         1
Inválido: DDD 41 não pertence ao estado RR e Inválido: fixo com dígito inicial incorreto     1
Inválido: DDD 41 não pertence ao estado TO e Inválido: fixo com dígito inicial incorreto     1
Inválido: DDD 11 não pertence ao estado BA e Inválido: fixo com dígito inicial incorreto     1
Inválido: DDD 11 não pertence ao estado nan                                                  1
Name: count, dtype: int64

In [125]:
df.isnull().sum()

ID                         0
Nome                       0
Email                      0
CPF                        0
Data de Nascimento         0
Telefone                   0
Estado                     0
Cidade                     0
Endereço                   0
Formação Acadêmica         0
Treinamentos Realizados    0
Estado_Telefone            1
telefone_limpo             0
estado_telefone            1
ddd_status                 0
num_status                 0
status_final               0
dtype: int64

In [126]:
df = df.drop(['telefone_limpo', 'estado_telefone', "ddd_status","num_status", "Estado_Telefone"], axis=1)
df.rename(columns={"status_final": "Telefone_status"}, inplace=True)

In [127]:
df.head()

,ID,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Cidade,Endereço,Formação Acadêmica,Treinamentos Realizados,Telefone_status
0,7,Sra. Vanessa Nogueira,vanessa.nogueira@exemplo,34512367890,1992-09-05,+55 (21) 9876-1234,RJ,Niterói,"Rua Mato Grosso, 192, Niterói - RJ",Ensino Médio Completo,"Excel Avançado, Segurança da Informação",Inválido: celular com tamanho incorreto
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 (11) 93220-4567,SP,São Paulo,"Rua Rio Branco, 831, São Paulo - SP",Tecnólogo em Análise de Sistemas,Segurança da Informação,Válido
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,+55 (19) 99765-3332,SP,Santos,"Rua Horizonte Azul, 779, Santos - SP",Sistemas de Informação,Scrum Foundation,Válido
3,10,Dr. Rafael Costa,rafael.costa@email.com,78965432100,1987-03-22,+55 (71) 91234-5678,BA,Feira de Santana,"Rua Cruzeiro do Sul, 162, Feira de Santana - BA",Ensino Médio Completo,"Desenvolvimento Web com React, Excel Avançado,...",Válido
4,11,Thiago Moura,thiago@dominio.com,12345678900,1990-01-12,+55 (21) 99999-0001,RJ,Niterói,"Rua do Sol, 121, Niterói - RJ",Engenharia de Software,"Desenvolvimento Web com React, Segurança da In...",Válido

In [128]:
df['Nome'] = df["Nome"].str.replace(r"^.*?\.\s*", "", regex=True).str.strip().str.title()

In [129]:
df["Nome"].apply(lambda x: x == x.title()).value_counts()

Nome
True    80
Name: count, dtype: int64

In [130]:
df['Formação Acadêmica'].value_counts()

Formação Acadêmica
Engenharia de Software                  19
Ensino Médio Completo                   18
Tecnólogo em Análise de Sistemas        17
Sistemas de Informação                  14
Bacharelado em Ciência da Computação    12
Name: count, dtype: int64

In [131]:
treinamentos_df = df['Treinamentos Realizados'].str.split(', ').explode().reset_index(drop=True).to_frame(name='Treinamento')

In [132]:
treinamentos_df.value_counts()

Treinamento
Segurança da Informação          35
Excel Avançado                   31
Desenvolvimento Web com React    30
Scrum Foundation                 30
Curso de Power BI                26
Name: count, dtype: int64

In [133]:
# def validar_cpf(cpf: str) -> bool:
#     cpf = re.sub(r'\D', '', str(cpf))

#     if len(cpf) != 11:
#         return False

#     if cpf == cpf[0] * 11:
#         return False

#     soma = sum(int(cpf[i]) * (10 - i) for i in range(9))
#     digito1 = (soma * 10) % 11
#     digito1 = 0 if digito1 == 10 else digito1

#     if digito1 != int(cpf[9]):
#         return False

#     soma = sum(int(cpf[i]) * (11 - i) for i in range(10))
#     digito2 = (soma * 10) % 11
#     digito2 = 0 if digito2 == 10 else digito2

#     if digito2 != int(cpf[10]):
#         return False

#     return True

In [134]:
# 1 - Criar coluna com CPF numérico
df['CPF_Limpo'] = df['CPF'].apply(lambda x: re.sub(r'\D', '', str(x)))

# 2 - Função de validação (somente tamanho e repetição)
def validar_cpf_basico(cpf_num):
    if len(cpf_num) != 11:
        return f"Inválido: possui {len(cpf_num)} dígitos (deve ter 11)"
    if cpf_num == cpf_num[0] * 11:
        return "Inválido: todos os dígitos são iguais"
    return "Válido"

# 3 - Aplicar função
df['Situacao_CPF'] = df['CPF_Limpo'].apply(validar_cpf_basico)
df.drop('CPF_Limpo', axis=1, inplace=True)

print(df)

    ID              Nome                        Email             CPF  \
0    7  Vanessa Nogueira     vanessa.nogueira@exemplo     34512367890
1    8    Eduardo Araújo       edu.araújo@empresa.com  024.878.550-22
2    9     Mariana Silva       mariana@dominio.com.br  123.456.789-00
3   10      Rafael Costa       rafael.costa@email.com     78965432100
4   11      Thiago Moura           thiago@dominio.com     12345678900
..  ..               ...                          ...             ...
75  76     Carla Martins       carla.martins@mail.com     45612398712
76  77      Roberto Dias       roberto.dias@email.com     78945678912
77  78     Larissa Costa       larissa.costa@mail.com     32198712312
78  79   Ricardo Almeida  ricardo.almeida@empresa.com     65412345612
79  80    Patrícia Souza   patricia.souza@dominio.com     78932178912

   Data de Nascimento             Telefone Estado            Cidade  \
0          1992-09-05   +55 (21) 9876-1234     RJ           Niterói
1          1980-07-30  +55 (11) 93220-4567     SP         São Paulo
2          1999-06-15  +55 (19) 99765-3332     SP            Santos
3          1987-03-22  +55 (71) 91234-5678     BA  Feira de Santana
4          1990-01-12  +55 (21) 99999-0001     RJ           Niterói
..                ...                  ...    ...               ...
75         1992-05-05  +55 (41) 91234-5789     RJ       Nova Iguaçu
76         1989-07-22  +55 (41) 99887-7776     RJ       Nova Iguaçu
77         1993-03-15  +55 (41) 98765-4321     RJ       Nova Iguaçu
78         1990-09-09  +55 (41) 91234-4333     RJ       Nova Iguaçu
79         1991-11-10  +55 (41) 99887-7553     RJ       Nova Iguaçu

                                           Endereço  \
0                Rua Mato Grosso, 192, Niterói - RJ
1               Rua Rio Branco, 831, São Paulo - SP
2              Rua Horizonte Azul, 779, Santos - SP
3   Rua Cruzeiro do Sul, 162, Feira de Santana - BA
4                     Rua do Sol, 121, Niterói - RJ
..                                              ...
75            Rua Bela Vista, 718, Nova Iguaçu - RJ
76              Rua Alvorada, 163, Nova Iguaçu - RJ
77            Rua Bela Vista, 540, Nova Iguaçu - RJ
78            Rua Bela Vista, 859, Nova Iguaçu - RJ
79            Rua Pernambuco, 561, Nova Iguaçu - RJ

                      Formação Acadêmica  \
0                  Ensino Médio Completo
1       Tecnólogo em Análise de Sistemas
2                 Sistemas de Informação
3                  Ensino Médio Completo
4                 Engenharia de Software
..                                   ...
75                Sistemas de Informação
76      Tecnólogo em Análise de Sistemas
77                Engenharia de Software
78                Engenharia de Software
79  Bacharelado em Ciência da Computação

                              Treinamentos Realizados  \
0             Excel Avançado, Segurança da Informação
1                             Segurança da Informação
2                                    Scrum Foundation
3   Desenvolvimento Web com React, Excel Avançado,...
4   Desenvolvimento Web com React, Segurança da In...
..                                                ...
75            Excel Avançado, Segurança da Informação
76                            Segurança da Informação
77  Segurança da Informação, Curso de Power BI, Sc...
78                                  Curso de Power BI
79  Desenvolvimento Web com React, Segurança da In...

                            Telefone_status Situacao_CPF
0   Inválido: celular com tamanho incorreto       Válido
1                                    Válido       Válido
2                                    Válido       Válido
3                                    Válido       Válido
4                                    Válido       Válido
..                                      ...          ...
75                                   Válido       Válido
76                                   Válido       Válido
77                                   Válido       Válido
78                                   Válido       Válido
79                                   Válido       Válido

[80 rows x 13 columns]

In [135]:
df['Situacao_CPF'].value_counts()

Situacao_CPF
Válido                                   78
Inválido: todos os dígitos são iguais     2
Name: count, dtype: int64

In [136]:
df.head()

,ID,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Cidade,Endereço,Formação Acadêmica,Treinamentos Realizados,Telefone_status,Situacao_CPF
0,7,Vanessa Nogueira,vanessa.nogueira@exemplo,34512367890,1992-09-05,+55 (21) 9876-1234,RJ,Niterói,"Rua Mato Grosso, 192, Niterói - RJ",Ensino Médio Completo,"Excel Avançado, Segurança da Informação",Inválido: celular com tamanho incorreto,Válido
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 (11) 93220-4567,SP,São Paulo,"Rua Rio Branco, 831, São Paulo - SP",Tecnólogo em Análise de Sistemas,Segurança da Informação,Válido,Válido
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,+55 (19) 99765-3332,SP,Santos,"Rua Horizonte Azul, 779, Santos - SP",Sistemas de Informação,Scrum Foundation,Válido,Válido
3,10,Rafael Costa,rafael.costa@email.com,78965432100,1987-03-22,+55 (71) 91234-5678,BA,Feira de Santana,"Rua Cruzeiro do Sul, 162, Feira de Santana - BA",Ensino Médio Completo,"Desenvolvimento Web com React, Excel Avançado,...",Válido,Válido
4,11,Thiago Moura,thiago@dominio.com,12345678900,1990-01-12,+55 (21) 99999-0001,RJ,Niterói,"Rua do Sol, 121, Niterói - RJ",Engenharia de Software,"Desenvolvimento Web com React, Segurança da In...",Válido,Válido

In [137]:
df["CPF"] = df['CPF'].astype(str).apply(lambda x: re.sub(r"\D", "", x))

df = df[df["CPF"].str.len() == 11]

df["CPF"] = df["CPF"].apply(lambda x: f"{x[:3]}.{x[3:6]}.{x[6:9]}-{x[9:]}")

df.head()

,ID,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Cidade,Endereço,Formação Acadêmica,Treinamentos Realizados,Telefone_status,Situacao_CPF
0,7,Vanessa Nogueira,vanessa.nogueira@exemplo,345.123.678-90,1992-09-05,+55 (21) 9876-1234,RJ,Niterói,"Rua Mato Grosso, 192, Niterói - RJ",Ensino Médio Completo,"Excel Avançado, Segurança da Informação",Inválido: celular com tamanho incorreto,Válido
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 (11) 93220-4567,SP,São Paulo,"Rua Rio Branco, 831, São Paulo - SP",Tecnólogo em Análise de Sistemas,Segurança da Informação,Válido,Válido
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,+55 (19) 99765-3332,SP,Santos,"Rua Horizonte Azul, 779, Santos - SP",Sistemas de Informação,Scrum Foundation,Válido,Válido
3,10,Rafael Costa,rafael.costa@email.com,789.654.321-00,1987-03-22,+55 (71) 91234-5678,BA,Feira de Santana,"Rua Cruzeiro do Sul, 162, Feira de Santana - BA",Ensino Médio Completo,"Desenvolvimento Web com React, Excel Avançado,...",Válido,Válido
4,11,Thiago Moura,thiago@dominio.com,123.456.789-00,1990-01-12,+55 (21) 99999-0001,RJ,Niterói,"Rua do Sol, 121, Niterói - RJ",Engenharia de Software,"Desenvolvimento Web com React, Segurança da In...",Válido,Válido

In [138]:
def converter_com_formatos(data):
    formatos = ['%Y-%m-%d', '%d-%m-%Y']
    for fmt in formatos:
        try:
            return pd.to_datetime(data, format=fmt, errors='raise')
        except (ValueError, TypeError):
            continue
    return pd.NaT

df["Data de Nascimento"].apply(converter_com_formatos).isnull().sum()

np.int64(0)

In [ ]:
df_exploded = df[['idColaborador', 'Treinamentos Realizados']].copy()

In [140]:
df_exploded

    ID                            Treinamentos Realizados
0    7            Excel Avançado, Segurança da Informação
1    8                            Segurança da Informação
2    9                                   Scrum Foundation
3   10  Desenvolvimento Web com React, Excel Avançado,...
4   11  Desenvolvimento Web com React, Segurança da In...
..  ..                                                ...
75  76            Excel Avançado, Segurança da Informação
76  77                            Segurança da Informação
77  78  Segurança da Informação, Curso de Power BI, Sc...
78  79                                  Curso de Power BI
79  80  Desenvolvimento Web com React, Segurança da In...

[80 rows x 2 columns]

In [141]:
df_exploded['Treinamentos Realizados'] = df_exploded['Treinamentos Realizados'].str.split(',')

In [142]:
df_dim_treinamentos = df_exploded.explode('Treinamentos Realizados')

In [143]:
df_dim_treinamentos['Treinamentos Realizados'] = df_dim_treinamentos['Treinamentos Realizados'].str.strip()

In [ ]:
# Use a variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "dc_Treinamentos_tratado.csv")

# A partir daqui, você usa a variável caminho_saida
df_dim_treinamentos.to_csv(caminho_saida, index=False)

In [ ]:
#df_dim_treinamentos.to_csv('../ArquivosExternos/dados_tratados_v2/dc_Treinamentos_tratado.csv', index=False)

In [ ]:
df_exploded2 = df[['idColaborador', 'Formação Acadêmica']].copy()

In [ ]:

# Use a variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "dc_Formacao_tratado.csv")

# A partir daqui, você usa a variável caminho_saida
df_exploded2.to_csv(caminho_saida, index=False)

In [ ]:
#df_exploded2.to_csv('../ArquivosExternos/dados_tratados_v2/dc_Formacao_tratado.csv', index=False)

In [146]:
df.head(1)

,ID,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Cidade,Endereço,Formação Acadêmica,Treinamentos Realizados,Telefone_status,Situacao_CPF
0,7,Vanessa Nogueira,vanessa.nogueira@exemplo,345.123.678-90,1992-09-05,+55 (21) 9876-1234,RJ,Niterói,"Rua Mato Grosso, 192, Niterói - RJ",Ensino Médio Completo,"Excel Avançado, Segurança da Informação",Inválido: celular com tamanho incorreto,Válido

In [ ]:
colaborador_202508051406 = df[['idColaborador', 'Nome','Email','CPF','Data de Nascimento','Telefone']].copy()

In [148]:
colaborador_202508051406 = colaborador_202508051406.rename(columns={
    'ID': 'id_colaborador',
    'Nome': 'nome_colaborador',
    'Email': 'email_colaborador',
    'CPF': 'cpf',
    'Data de Nascimento': 'data_nascimento',
    'Telefone': 'telefone'
})

In [149]:
colaborador_202508051406.head()

,id_colaborador,nome_colaborador,email_colaborador,cpf,data_nascimento,telefone
0,7,Vanessa Nogueira,vanessa.nogueira@exemplo,345.123.678-90,1992-09-05,+55 (21) 9876-1234
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 (11) 93220-4567
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,+55 (19) 99765-3332
3,10,Rafael Costa,rafael.costa@email.com,789.654.321-00,1987-03-22,+55 (71) 91234-5678
4,11,Thiago Moura,thiago@dominio.com,123.456.789-00,1990-01-12,+55 (21) 99999-0001

In [151]:
df['Email'].str.extract(r'@([\-./com]+)').value_counts() #\.-

0
m    16
Name: count, dtype: int64

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       80 non-null     int64
 1   Nome                     80 non-null     object
 2   Email                    80 non-null     object
 3   CPF                      80 non-null     object
 4   Data de Nascimento       80 non-null     datetime64[ns]
 5   Telefone                 80 non-null     object
 6   Estado                   80 non-null     object
 7   Cidade                   80 non-null     object
 8   Endereço                 80 non-null     object
 9   Formação Acadêmica       80 non-null     object
 10  Treinamentos Realizados  80 non-null     object
 11  Telefone_status          80 non-null     object
 12  Situacao_CPF             80 non-null     object
dtypes: datetime64[ns](1), int64(1), object(11)
memory usage: 8.3+ KB

In [153]:
df["Cidade"].value_counts()

Cidade
Nova Iguaçu          20
Niterói              11
Rio de Janeiro        8
Santos                6
Porto Alegre          5
Caxias do Sul         5
Campinas              4
São Paulo             3
Feira de Santana      3
Contagem              2
São Luís              2
Juazeiro do Norte     2
Florianópolis         1
Brasília              1
Cuiabá                1
Londrina              1
Maceió                1
Natal                 1
Goiânia               1
Palmas                1
Boa Vista             1
Name: count, dtype: int64

In [154]:
df.head()

,ID,Nome,Email,CPF,Data de Nascimento,Telefone,Estado,Cidade,Endereço,Formação Acadêmica,Treinamentos Realizados,Telefone_status,Situacao_CPF
0,7,Vanessa Nogueira,vanessa.nogueira@exemplo,345.123.678-90,1992-09-05,+55 (21) 9876-1234,RJ,Niterói,"Rua Mato Grosso, 192, Niterói - RJ",Ensino Médio Completo,"Excel Avançado, Segurança da Informação",Inválido: celular com tamanho incorreto,Válido
1,8,Eduardo Araújo,edu.araújo@empresa.com,024.878.550-22,1980-07-30,+55 (11) 93220-4567,SP,São Paulo,"Rua Rio Branco, 831, São Paulo - SP",Tecnólogo em Análise de Sistemas,Segurança da Informação,Válido,Válido
2,9,Mariana Silva,mariana@dominio.com.br,123.456.789-00,1999-06-15,+55 (19) 99765-3332,SP,Santos,"Rua Horizonte Azul, 779, Santos - SP",Sistemas de Informação,Scrum Foundation,Válido,Válido
3,10,Rafael Costa,rafael.costa@email.com,789.654.321-00,1987-03-22,+55 (71) 91234-5678,BA,Feira de Santana,"Rua Cruzeiro do Sul, 162, Feira de Santana - BA",Ensino Médio Completo,"Desenvolvimento Web com React, Excel Avançado,...",Válido,Válido
4,11,Thiago Moura,thiago@dominio.com,123.456.789-00,1990-01-12,+55 (21) 99999-0001,RJ,Niterói,"Rua do Sol, 121, Niterói - RJ",Engenharia de Software,"Desenvolvimento Web com React, Segurança da In...",Válido,Válido

In [155]:
drop_columns = ['Formação Acadêmica', 'Treinamentos Realizados']
df = df.drop(columns=drop_columns)

In [ ]:

# variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "dc_DadosPrimarios_tratado.csv")

# variável caminho_saida
df.to_csv(caminho_saida, index=False)

In [ ]:
#df.to_csv('../ArquivosExternos/dados_tratados_v2/dc_DadosPrimarios_tratado.csv', index=False)