In [ ]:
import pandas as pd
import os
import sys

In [ ]:
# Adiciona o diretório-raiz do projeto ao sys.path
sys.path.append('/app')

import importlib
import utils.conexao
importlib.reload(utils.conexao)
# Importa a função e a variável do schema do módulo de conexão
from utils.conexao import get_dados_origem, SCHEMA_ORIGEM

# consulta
query = f'SELECT * FROM "{SCHEMA_ORIGEM}"."empresa";'
df_empresa = get_dados_origem(query) 

if df_empresa is not None:
    print("Extração concluída:")
    print(df_empresa.head())

In [3]:
#visualizar 10 linhas
df_empresa.head(10)

,id_empresa,cnpj_empresa,contato_empresa,endereco_empresa,nome_empresa,setor_empresa
0,1,116.586.741/0985-70,21987654321,"Rua das Flores, 123, RJ",Empresa Alfa,TI
1,2,21652281483133,11987654321,"Av. Brasil, 456, SP",Empresa Beta,ti
2,3,68.653.207/8626-34,31999988877,"Praça Central, 789, MG",Empresa Gama,Tecnologia
3,4,34.123.456/0001-99,27987654321,"Av. das Américas, 1000, RJ",Tech Soluções,Tecnologia
4,5,10293847560123,11333445566,"Rua XV de Novembro, 456, SP",Inova Sistemas,TI
5,6,45.678.901/0001-12,31912345678,"Rua da Bahia, 300, MG",Data Insights,Análise de Dados
6,7,98765432100012,21988776655,"Rua São Paulo, 777, RJ",Global Soft,TI
7,8,12.345.678/0001-90,11332244556,"Av. Paulista, 1500, SP",NextGen Tech,Tecnologia
8,9,56789012345678,51999887766,"Rua das Flores, 99, RS",RS Sistemas,TI
9,10,23.456.789/0001-11,41322114455,"Rua XV, 123, SC",SC Tecnologia,TI

In [4]:
df_empresa.isnull().sum()

id_empresa          0
cnpj_empresa        0
contato_empresa     0
endereco_empresa    0
nome_empresa        0
setor_empresa       0
dtype: int64

In [5]:
#ver informações gerais da tabela
df_empresa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_empresa        10 non-null     int64
 1   cnpj_empresa      10 non-null     object
 2   contato_empresa   10 non-null     object
 3   endereco_empresa  10 non-null     object
 4   nome_empresa      10 non-null     object
 5   setor_empresa     10 non-null     object
dtypes: int64(1), object(5)
memory usage: 612.0+ bytes

In [ ]:
# Criar o dicionário com os dados da nova linha
nova_linha = {
    "id_empresa": 11,
    "cnpj_empresa": "12.345.678/0001-55",
    "contato_empresa": "242237-3668",
    "endereco_empresa": "Rua Afrânio Melo Franco, 333, RJ",
    "nome_empresa": "T2M",
    "setor_empresa": "TI"
}

# Adicionar ao final usando loc
df_empresa.loc[len(df_empresa)] = nova_linha

In [6]:
#tratando nome das empresas
df_empresa["nome_empresa"] = df_empresa["nome_empresa"].str.replace("Empresa", "", case=False)
df_empresa.head(10)

,id_empresa,cnpj_empresa,contato_empresa,endereco_empresa,nome_empresa,setor_empresa
0,1,116.586.741/0985-70,21987654321,"Rua das Flores, 123, RJ",Alfa,TI
1,2,21652281483133,11987654321,"Av. Brasil, 456, SP",Beta,ti
2,3,68.653.207/8626-34,31999988877,"Praça Central, 789, MG",Gama,Tecnologia
3,4,34.123.456/0001-99,27987654321,"Av. das Américas, 1000, RJ",Tech Soluções,Tecnologia
4,5,10293847560123,11333445566,"Rua XV de Novembro, 456, SP",Inova Sistemas,TI
5,6,45.678.901/0001-12,31912345678,"Rua da Bahia, 300, MG",Data Insights,Análise de Dados
6,7,98765432100012,21988776655,"Rua São Paulo, 777, RJ",Global Soft,TI
7,8,12.345.678/0001-90,11332244556,"Av. Paulista, 1500, SP",NextGen Tech,Tecnologia
8,9,56789012345678,51999887766,"Rua das Flores, 99, RS",RS Sistemas,TI
9,10,23.456.789/0001-11,41322114455,"Rua XV, 123, SC",SC Tecnologia,TI

In [7]:
#padronizar setor da empresa

def padronizar_setor(valor):
    if pd.isna(valor):
        return valor
    valor = valor.strip()

    if len(valor) == 2:
        return valor.upper()
    else:
        # Aplica o title
        valor = valor.title()

        # Lista de preposições que devem ficar em minúsculo
        preposicoes = ["De", "Da", "Do", "Das", "Dos", "Em", "Por", "Sob", "A", "À", "E"]

        # Corrige preposições
        palavras = valor.split()
        palavras_corrigidas = [palavra.lower() if palavra in preposicoes else palavra for palavra in palavras]

        # Garante que a primeira palavra continue com inicial maiúscula
        if palavras_corrigidas:
            palavras_corrigidas[0] = palavras_corrigidas[0].capitalize()

        return ' '.join(palavras_corrigidas)

df_empresa["setor_empresa"] = df_empresa["setor_empresa"].apply(padronizar_setor)
df_empresa.head(10)

,id_empresa,cnpj_empresa,contato_empresa,endereco_empresa,nome_empresa,setor_empresa
0,1,116.586.741/0985-70,21987654321,"Rua das Flores, 123, RJ",Alfa,TI
1,2,21652281483133,11987654321,"Av. Brasil, 456, SP",Beta,TI
2,3,68.653.207/8626-34,31999988877,"Praça Central, 789, MG",Gama,Tecnologia
3,4,34.123.456/0001-99,27987654321,"Av. das Américas, 1000, RJ",Tech Soluções,Tecnologia
4,5,10293847560123,11333445566,"Rua XV de Novembro, 456, SP",Inova Sistemas,TI
5,6,45.678.901/0001-12,31912345678,"Rua da Bahia, 300, MG",Data Insights,Análise de Dados
6,7,98765432100012,21988776655,"Rua São Paulo, 777, RJ",Global Soft,TI
7,8,12.345.678/0001-90,11332244556,"Av. Paulista, 1500, SP",NextGen Tech,Tecnologia
8,9,56789012345678,51999887766,"Rua das Flores, 99, RS",RS Sistemas,TI
9,10,23.456.789/0001-11,41322114455,"Rua XV, 123, SC",SC Tecnologia,TI

In [8]:
#tratamento de endereço
# Separar a coluna 'endereco_empresa' em 'logradouro', 'numero' e 'estado'
df_empresa[['logradouro', 'numero', 'estado']] = df_empresa['endereco_empresa'].str.extract(r'^(.*?),\s*(\d+),\s*([A-Z]{2})$')

# Exibir as novas colunas
print(df_empresa[['endereco_empresa', 'logradouro', 'numero', 'estado']])

              endereco_empresa          logradouro numero estado
0      Rua das Flores, 123, RJ      Rua das Flores    123     RJ
1          Av. Brasil, 456, SP          Av. Brasil    456     SP
2       Praça Central, 789, MG       Praça Central    789     MG
3   Av. das Américas, 1000, RJ    Av. das Américas   1000     RJ
4  Rua XV de Novembro, 456, SP  Rua XV de Novembro    456     SP
5        Rua da Bahia, 300, MG        Rua da Bahia    300     MG
6       Rua São Paulo, 777, RJ       Rua São Paulo    777     RJ
7       Av. Paulista, 1500, SP        Av. Paulista   1500     SP
8       Rua das Flores, 99, RS      Rua das Flores     99     RS
9              Rua XV, 123, SC              Rua XV    123     SC

In [9]:
df_empresa.drop(columns='endereco_empresa', inplace=True) #apagar coluna antiga
df_empresa.head(10)

,id_empresa,cnpj_empresa,contato_empresa,nome_empresa,setor_empresa,logradouro,numero,estado
0,1,116.586.741/0985-70,21987654321,Alfa,TI,Rua das Flores,123,RJ
1,2,21652281483133,11987654321,Beta,TI,Av. Brasil,456,SP
2,3,68.653.207/8626-34,31999988877,Gama,Tecnologia,Praça Central,789,MG
3,4,34.123.456/0001-99,27987654321,Tech Soluções,Tecnologia,Av. das Américas,1000,RJ
4,5,10293847560123,11333445566,Inova Sistemas,TI,Rua XV de Novembro,456,SP
5,6,45.678.901/0001-12,31912345678,Data Insights,Análise de Dados,Rua da Bahia,300,MG
6,7,98765432100012,21988776655,Global Soft,TI,Rua São Paulo,777,RJ
7,8,12.345.678/0001-90,11332244556,NextGen Tech,Tecnologia,Av. Paulista,1500,SP
8,9,56789012345678,51999887766,RS Sistemas,TI,Rua das Flores,99,RS
9,10,23.456.789/0001-11,41322114455,SC Tecnologia,TI,Rua XV,123,SC

In [ ]:
import importlib
import utils.valida_telefone as valida_telefone
importlib.reload(valida_telefone)   # recarrega o módulo com as mudanças
from utils.valida_telefone import aplicar_validacao

# aplicando validação e formatação de telefone
df_empresa = aplicar_validacao(df_empresa, "contato_empresa", "estado")

df_empresa.head(20)

,id_empresa,cnpj_empresa,contato_empresa,nome_empresa,setor_empresa,logradouro,numero,estado,telefone_limpo,estado_telefone,ddd_status,num_status,status_final
0,1,116.586.741/0985-70,+55 (21) 98765-4321,Alfa,TI,Rua das Flores,123,RJ,21987654321,RJ,Válido,Válido,Válido
1,2,21652281483133,+55 (11) 98765-4321,Beta,TI,Av. Brasil,456,SP,11987654321,SP,Válido,Válido,Válido
2,3,68.653.207/8626-34,+55 (31) 99998-8877,Gama,Tecnologia,Praça Central,789,MG,31999988877,MG,Válido,Válido,Válido
3,4,34.123.456/0001-99,+55 (27) 98765-4321,Tech Soluções,Tecnologia,Av. das Américas,1000,RJ,27987654321,RJ,Inválido: DDD 27 não pertence ao estado RJ,Válido,Inválido: DDD 27 não pertence ao estado RJ
4,5,10293847560123,+55 (11) 33344-5566,Inova Sistemas,TI,Rua XV de Novembro,456,SP,11333445566,SP,Válido,Inválido: celular sem 9 inicial,Inválido: celular sem 9 inicial
5,6,45.678.901/0001-12,+55 (31) 91234-5678,Data Insights,Análise de Dados,Rua da Bahia,300,MG,31912345678,MG,Válido,Válido,Válido
6,7,98765432100012,+55 (21) 98877-6655,Global Soft,TI,Rua São Paulo,777,RJ,21988776655,RJ,Válido,Válido,Válido
7,8,12.345.678/0001-90,+55 (11) 33224-4556,NextGen Tech,Tecnologia,Av. Paulista,1500,SP,11332244556,SP,Válido,Inválido: celular sem 9 inicial,Inválido: celular sem 9 inicial
8,9,56789012345678,+55 (51) 99988-7766,RS Sistemas,TI,Rua das Flores,99,RS,51999887766,RS,Válido,Válido,Válido
9,10,23.456.789/0001-11,+55 (41) 32211-4455,SC Tecnologia,TI,Rua XV,123,SC,41322114455,SC,Inválido: DDD 41 não pertence ao estado SC,Inválido: celular sem 9 inicial,Inválido: DDD 41 não pertence ao estado SC e I...

In [11]:
#contar resultados
df_empresa["status_final"].value_counts()

status_final
Válido                                                                          6
Inválido: celular sem 9 inicial                                                 2
Inválido: DDD 27 não pertence ao estado RJ                                      1
Inválido: DDD 41 não pertence ao estado SC e Inválido: celular sem 9 inicial    1
Name: count, dtype: int64

In [12]:
df_empresa.head(10)

,id_empresa,cnpj_empresa,contato_empresa,nome_empresa,setor_empresa,logradouro,numero,estado,telefone_limpo,estado_telefone,ddd_status,num_status,status_final
0,1,116.586.741/0985-70,+55 (21) 98765-4321,Alfa,TI,Rua das Flores,123,RJ,21987654321,RJ,Válido,Válido,Válido
1,2,21652281483133,+55 (11) 98765-4321,Beta,TI,Av. Brasil,456,SP,11987654321,SP,Válido,Válido,Válido
2,3,68.653.207/8626-34,+55 (31) 99998-8877,Gama,Tecnologia,Praça Central,789,MG,31999988877,MG,Válido,Válido,Válido
3,4,34.123.456/0001-99,+55 (27) 98765-4321,Tech Soluções,Tecnologia,Av. das Américas,1000,RJ,27987654321,RJ,Inválido: DDD 27 não pertence ao estado RJ,Válido,Inválido: DDD 27 não pertence ao estado RJ
4,5,10293847560123,+55 (11) 33344-5566,Inova Sistemas,TI,Rua XV de Novembro,456,SP,11333445566,SP,Válido,Inválido: celular sem 9 inicial,Inválido: celular sem 9 inicial
5,6,45.678.901/0001-12,+55 (31) 91234-5678,Data Insights,Análise de Dados,Rua da Bahia,300,MG,31912345678,MG,Válido,Válido,Válido
6,7,98765432100012,+55 (21) 98877-6655,Global Soft,TI,Rua São Paulo,777,RJ,21988776655,RJ,Válido,Válido,Válido
7,8,12.345.678/0001-90,+55 (11) 33224-4556,NextGen Tech,Tecnologia,Av. Paulista,1500,SP,11332244556,SP,Válido,Inválido: celular sem 9 inicial,Inválido: celular sem 9 inicial
8,9,56789012345678,+55 (51) 99988-7766,RS Sistemas,TI,Rua das Flores,99,RS,51999887766,RS,Válido,Válido,Válido
9,10,23.456.789/0001-11,+55 (41) 32211-4455,SC Tecnologia,TI,Rua XV,123,SC,41322114455,SC,Inválido: DDD 41 não pertence ao estado SC,Inválido: celular sem 9 inicial,Inválido: DDD 41 não pertence ao estado SC e I...

In [13]:
#validação cnpj

import re #importação da biblioteca re para facilitar validação

def validar_cnpj_com_motivo(cnpj):
    cnpj = re.sub(r'\D', '', str(cnpj))  # Remove tudo que não for número

    if len(cnpj) != 14:
        return "Inválido: tamanho incorreto"

    if len(set(cnpj)) == 1:
        return "Inválido: dígitos repetidos"

    return "Válido"

In [14]:
df_empresa['cnpj_empresa'].apply(validar_cnpj_com_motivo).value_counts()

cnpj_empresa
Válido                         9
Inválido: tamanho incorreto    1
Name: count, dtype: int64

In [15]:
df_empresa['cnpj_motivo'] = df_empresa['cnpj_empresa'].apply(validar_cnpj_com_motivo)

In [16]:
df_empresa.head(15)

,id_empresa,cnpj_empresa,contato_empresa,nome_empresa,setor_empresa,logradouro,numero,estado,telefone_limpo,estado_telefone,ddd_status,num_status,status_final,cnpj_motivo
0,1,116.586.741/0985-70,+55 (21) 98765-4321,Alfa,TI,Rua das Flores,123,RJ,21987654321,RJ,Válido,Válido,Válido,Inválido: tamanho incorreto
1,2,21652281483133,+55 (11) 98765-4321,Beta,TI,Av. Brasil,456,SP,11987654321,SP,Válido,Válido,Válido,Válido
2,3,68.653.207/8626-34,+55 (31) 99998-8877,Gama,Tecnologia,Praça Central,789,MG,31999988877,MG,Válido,Válido,Válido,Válido
3,4,34.123.456/0001-99,+55 (27) 98765-4321,Tech Soluções,Tecnologia,Av. das Américas,1000,RJ,27987654321,RJ,Inválido: DDD 27 não pertence ao estado RJ,Válido,Inválido: DDD 27 não pertence ao estado RJ,Válido
4,5,10293847560123,+55 (11) 33344-5566,Inova Sistemas,TI,Rua XV de Novembro,456,SP,11333445566,SP,Válido,Inválido: celular sem 9 inicial,Inválido: celular sem 9 inicial,Válido
5,6,45.678.901/0001-12,+55 (31) 91234-5678,Data Insights,Análise de Dados,Rua da Bahia,300,MG,31912345678,MG,Válido,Válido,Válido,Válido
6,7,98765432100012,+55 (21) 98877-6655,Global Soft,TI,Rua São Paulo,777,RJ,21988776655,RJ,Válido,Válido,Válido,Válido
7,8,12.345.678/0001-90,+55 (11) 33224-4556,NextGen Tech,Tecnologia,Av. Paulista,1500,SP,11332244556,SP,Válido,Inválido: celular sem 9 inicial,Inválido: celular sem 9 inicial,Válido
8,9,56789012345678,+55 (51) 99988-7766,RS Sistemas,TI,Rua das Flores,99,RS,51999887766,RS,Válido,Válido,Válido,Válido
9,10,23.456.789/0001-11,+55 (41) 32211-4455,SC Tecnologia,TI,Rua XV,123,SC,41322114455,SC,Inválido: DDD 41 não pertence ao estado SC,Inválido: celular sem 9 inicial,Inválido: DDD 41 não pertence ao estado SC e I...,Válido

In [17]:
#padronizando cnpj
df_empresa["cnpj_empresa"] = (
    df_empresa["cnpj_empresa"]
    .astype(str)
    .str.replace(r'\D', '', regex=True)  # Remove tudo que não é número
    .apply(lambda c: f"{c[:2]}.{c[2:5]}.{c[5:8]}/{c[8:12]}-{c[12:]}" )
)

In [18]:
df_empresa.drop(columns=['telefone_limpo',	'estado_telefone',	'ddd_status',	'num_status'], inplace=True)

In [19]:
df_empresa.rename(columns={
    'status_final':'Status_Telefone',
    'cnpj_motivo': 'Status_cnpj'
}, inplace=True)

In [20]:
df_empresa.rename(columns=lambda col: "_".join(p.capitalize() for p in col.split("_")), inplace=True)

In [21]:
df_empresa.head(15)

,Id_Empresa,Cnpj_Empresa,Contato_Empresa,Nome_Empresa,Setor_Empresa,Logradouro,Numero,Estado,Status_Telefone,Status_Cnpj
0,1,11.658.674/1098-570,+55 (21) 98765-4321,Alfa,TI,Rua das Flores,123,RJ,Válido,Inválido: tamanho incorreto
1,2,21.652.281/4831-33,+55 (11) 98765-4321,Beta,TI,Av. Brasil,456,SP,Válido,Válido
2,3,68.653.207/8626-34,+55 (31) 99998-8877,Gama,Tecnologia,Praça Central,789,MG,Válido,Válido
3,4,34.123.456/0001-99,+55 (27) 98765-4321,Tech Soluções,Tecnologia,Av. das Américas,1000,RJ,Inválido: DDD 27 não pertence ao estado RJ,Válido
4,5,10.293.847/5601-23,+55 (11) 33344-5566,Inova Sistemas,TI,Rua XV de Novembro,456,SP,Inválido: celular sem 9 inicial,Válido
5,6,45.678.901/0001-12,+55 (31) 91234-5678,Data Insights,Análise de Dados,Rua da Bahia,300,MG,Válido,Válido
6,7,98.765.432/1000-12,+55 (21) 98877-6655,Global Soft,TI,Rua São Paulo,777,RJ,Válido,Válido
7,8,12.345.678/0001-90,+55 (11) 33224-4556,NextGen Tech,Tecnologia,Av. Paulista,1500,SP,Inválido: celular sem 9 inicial,Válido
8,9,56.789.012/3456-78,+55 (51) 99988-7766,RS Sistemas,TI,Rua das Flores,99,RS,Válido,Válido
9,10,23.456.789/0001-11,+55 (41) 32211-4455,SC Tecnologia,TI,Rua XV,123,SC,Inválido: DDD 41 não pertence ao estado SC e I...,Válido

In [ ]:
#df_empresa.to_csv("../ArquivosPostgresql/dados_tratados_postgresql_v2/empresa_postgres_tratado.csv", index=False)

In [ ]:

# variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "empresa_postgres_tratado.csv")

# variável caminho_saida
df_empresa.to_csv(caminho_saida, index=False)