In [26]:
import pandas as pd

In [ ]:
# Carrega os dados do arquivo CSV
#df = pd.read_csv('../ArquivosExternos/dados_tratados_v2/dc_Certificacao_tratado.csv')

In [ ]:
import os

# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_tratados_v2", "dc_Certificacao_tratado.csv")

df = pd.read_csv(caminho_completo)

In [28]:
df.head()

   ID                                Certificacao        Data
0   1              PowerBI Data Analyst Associate  2024-04-29
1   4                      DevOps Engineer Expert  2019-03-07
2   6              PowerBI Data Analyst Associate  2023-03-07
3   8              PowerBI Data Analyst Associate  2022-08-01
4  11  Engenheiro de Segurança Associado do Azure  2025-07-16

In [ ]:
# Converte a coluna 'Data' para o formato de data e hora para facilitar a análise
df['Data'] = pd.to_datetime(df['Data'])

In [ ]:
df['idColaborador'] = df['idColaborador'].astype(int)

In [ ]:
import sys
import os
# Adiciona o diretório-raiz do projeto ao sys.path
sys.path.append('/app')


import importlib
import utils.modelagem_utils
importlib.reload(utils.modelagem_utils)   # recarrega o módulo com as mudanças
from utils.modelagem_utils import criar_tabelas_dimensao_e_fato

# Cria as tabelas de dimensão e fato para a certificação
# função genérica para criar as tabelas
dim_certificacao, fato_certificacao = criar_tabelas_dimensao_e_fato(
    df=df,
    nome_coluna_dimensao='Certificacao',
    nome_coluna_id_fato='idColaborador',
    nome_tabela_dimensao='dim_Certificacao',
    nome_tabela_fato='fato_Certificacao',
    outras_colunas_fato=['Data']
)

In [31]:
# Exibe as primeiras linhas das tabelas criadas para verificação
print("Tabela de Dimensões de Certificações (dim_certificacao):")
dim_certificacao.head()

Tabela de Dimensões de Certificações (dim_certificacao):

   idCertificacao                                Certificacao
0               1              PowerBI Data Analyst Associate
1               2                      DevOps Engineer Expert
2               3  Engenheiro de Segurança Associado do Azure
3               4               Cybersecurity Architec Expert
4               5     Analista de Dados Associado de Power BI

In [32]:
print("\nTabela de Ligação (fato_certificacao):")
fato_certificacao.head()

Tabela de Ligação (fato_certificacao):

   idColaborador  idCertificacao       Data
0              1               1 2024-04-29
1              4               2 2019-03-07
2              6               1 2023-03-07
3              8               1 2022-08-01
4             11               3 2025-07-16