## Cria uma tabela dimensão e outra fato

In [6]:
import pandas as pd

In [ ]:
#df=pd.read_csv('../ArquivosExternos/dados_tratados_v2/dc_Formacao_tratado.csv')

In [ ]:
import os

# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_tratados_v2", "dc_Formacao_tratado.csv")

df = pd.read_csv(caminho_completo)

In [8]:
df.head(20)

    ID                    Formação Acadêmica
0    7                 Ensino Médio Completo
1    8      Tecnólogo em Análise de Sistemas
2    9                Sistemas de Informação
3   10                 Ensino Médio Completo
4   11                Engenharia de Software
5   12                Engenharia de Software
6   13      Tecnólogo em Análise de Sistemas
7   14      Tecnólogo em Análise de Sistemas
8   15      Tecnólogo em Análise de Sistemas
9   16  Bacharelado em Ciência da Computação
10  17      Tecnólogo em Análise de Sistemas
11  18                Sistemas de Informação
12  19                 Ensino Médio Completo
13  20                Engenharia de Software
14  21  Bacharelado em Ciência da Computação
15  22  Bacharelado em Ciência da Computação
16  23                 Ensino Médio Completo
17  24      Tecnólogo em Análise de Sistemas
18  25      Tecnólogo em Análise de Sistemas
19  26                 Ensino Médio Completo

In [ ]:
# Renomeia a coluna 'ID' para 'idColaborador' para maior clareza
df.rename(columns={'Formação Acadêmica' : 'Formacao_Academica'}, inplace=True)

In [ ]:
import sys
# Adiciona o diretório-raiz do projeto ao sys.path
sys.path.append('/app')


import importlib
import utils.modelagem_utils
importlib.reload(utils.modelagem_utils)   # recarrega o módulo com as mudanças
from utils.modelagem_utils import criar_tabelas_dimensao_e_fato

# Chamada função para criar as tabelas
dim_formacao, fato_formacao = criar_tabelas_dimensao_e_fato(
    df=df,
    nome_coluna_dimensao='Formacao_Academica',
    nome_coluna_id_fato='idColaborador',
    nome_tabela_dimensao='dim_Formacao',
    nome_tabela_fato='fato_Formacao',
)

In [11]:
print("Dimensão (head):")
dim_formacao.head(20)

Dimensão (head):

   idFormacao_Academica                    Formacao_Academica
0                     1                 Ensino Médio Completo
1                     2      Tecnólogo em Análise de Sistemas
2                     3                Sistemas de Informação
3                     4                Engenharia de Software
4                     5  Bacharelado em Ciência da Computação

In [12]:
print("\nFato (head):")
fato_formacao.head(20)

Fato (head):

    idColaborador  idFormacao_Academica
0               7                     1
1               8                     2
2               9                     3
3              10                     1
4              11                     4
5              12                     4
6              13                     2
7              14                     2
8              15                     2
9              16                     5
10             17                     2
11             18                     3
12             19                     1
13             20                     4
14             21                     5
15             22                     5
16             23                     1
17             24                     2
18             25                     2
19             26                     1