In [3]:
import pandas as pd

In [ ]:
#df=pd.read_csv("../ArquivosExternos/dados_tratados_v2/dc_Treinamentos_tratado.csv")

In [ ]:
import os

# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_tratados_v2", "dc_Treinamentos_tratado.csv")

df = pd.read_csv(caminho_completo)

In [5]:
df.head(20)

    ID        Treinamentos Realizados
0    7                 Excel Avançado
1    7        Segurança da Informação
2    8        Segurança da Informação
3    9               Scrum Foundation
4   10  Desenvolvimento Web com React
5   10                 Excel Avançado
6   10        Segurança da Informação
7   11  Desenvolvimento Web com React
8   11        Segurança da Informação
9   12                 Excel Avançado
10  13  Desenvolvimento Web com React
11  13                 Excel Avançado
12  13        Segurança da Informação
13  14                 Excel Avançado
14  14               Scrum Foundation
15  15        Segurança da Informação
16  15                 Excel Avançado
17  15              Curso de Power BI
18  16               Scrum Foundation
19  17  Desenvolvimento Web com React

In [ ]:
df.rename(columns={'Treinamentos Realizados' : 'Treinamentos_Realizados'}, inplace=True)

In [ ]:
import sys
# Adiciona o diretório-raiz do projeto ao sys.path
sys.path.append('/app')


import importlib
import utils.modelagem_utils
importlib.reload(utils.modelagem_utils)   # recarrega o módulo com as mudanças
from utils.modelagem_utils import criar_tabelas_dimensao_e_fato

# Chama função para criar as tabelas
dim_treinamentos, fato_treinamentos = criar_tabelas_dimensao_e_fato(
    df=df,
    nome_coluna_dimensao='Treinamentos_Realizados',
    nome_coluna_id_fato='idColaborador',
    nome_tabela_dimensao='dim_Treinamentos',
    nome_tabela_fato='fato_Treinamentos',
)

In [8]:
# Exibe as primeiras linhas das tabelas criadas para verificação
print("Tabela de Dimensões de Treinamentos (dim_treinamentos):")
dim_treinamentos.head(20)

Tabela de Dimensões de Treinamentos (dim_treinamentos):

   idTreinamentos_Realizados        Treinamentos_Realizados
0                          1                 Excel Avançado
1                          2        Segurança da Informação
2                          3               Scrum Foundation
3                          4  Desenvolvimento Web com React
4                          5              Curso de Power BI

In [9]:
print("\nTabela de Ligação (fato_treinamentos):")
fato_treinamentos.head(20)

Tabela de Ligação (fato_treinamentos):

    idColaborador  idTreinamentos_Realizados
0               7                          1
1               7                          2
2               8                          2
3               9                          3
4              10                          4
5              10                          1
6              10                          2
7              11                          4
8              11                          2
9              12                          1
10             13                          4
11             13                          1
12             13                          2
13             14                          1
14             14                          3
15             15                          2
16             15                          1
17             15                          5
18             16                          3
19             17                          4