In [ ]:
import pandas as pd
import re
import os

In [ ]:
#df = pd.read_csv("../ArquivosExternos/dados_brutos/dados_colaboradores 1(DataAdmissao).csv")

In [ ]:
# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_brutos", "dados_colaboradores 1(DataAdmissao).csv")

df = pd.read_csv(caminho_completo)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    80 non-null     object
 1   Id      80 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.4+ KB

In [23]:
df = df[['Id', 'Data']]
display(df.head())

   Id          Data
0   1      1/3/2002
1   2  15/06/2002
2   3  22/09/2002
3   4     5/12/2002
4   5  18/03/2003

In [24]:
df.head()

   Id          Data
0   1      1/3/2002
1   2  15/06/2002
2   3  22/09/2002
3   4     5/12/2002
4   5  18/03/2003

In [25]:
def limpar_e_converter(data):
    data = re.sub(r"[^0-9]+", "-", data)

    data = data.strip("-")

    return pd.to_datetime(data, dayfirst=True, errors="coerce")

df["Data"] = df["Data"].apply(limpar_e_converter)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      80 non-null     int64
 1   Data    80 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 1.4 KB

In [27]:
df.head()

   Id       Data
0   1 2002-03-01
1   2 2002-06-15
2   3 2002-09-22
3   4 2002-12-05
4   5 2003-03-18

In [ ]:


#variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "dc_DataAdmissao_tratado.csv")

#  variável caminho_saida
df.to_csv(caminho_saida, index=False)

In [ ]:
#df.to_csv("../ArquivosExternos/dados_tratados_v2/dc_DataAdmissao_tratado.csv", index=False)