In [ ]:
import pandas as pd
import re
import os

In [ ]:
#df_certificacoes = pd.read_csv('../ArquivosExternos/dados_brutos/dados_colaboradores 1(Certificacoes).csv')

In [ ]:
# variável de ambiente para construir o caminho
caminho_base = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_completo = os.path.join(caminho_base, "dados_brutos", "dados_colaboradores 1(DadosCertificações).csv")

df_certificacoes = pd.read_csv(caminho_completo)

In [20]:
df_certificacoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             80 non-null     int64
 1   Certificação   17 non-null     object
 2   data           17 non-null     object
 3   certificação   16 non-null     object
 4   data.1         15 non-null     object
 5   certificação   11 non-null     object
 6   data.2         10 non-null     object
dtypes: int64(1), object(6)
memory usage: 4.5+ KB

In [ ]:
df_certificacoes.rename(columns={'ID': 'idColaborador'}, inplace=True)

In [21]:
# Remove espaços antes/depois dos nomes das colunas e normaliza caracteres especiais
df_certificacoes.columns = df_certificacoes.columns.str.strip()

# Reatribui os nomes corretamente via posição
df_certificacoes.columns.values[1] = 'Certificacao_1'
df_certificacoes.columns.values[2] = 'Data_1'
df_certificacoes.columns.values[3] = 'Certificacao_2'
df_certificacoes.columns.values[4] = 'Data_2'
df_certificacoes.columns.values[5] = 'Certificacao_3'
df_certificacoes.columns.values[6] = 'Data_3'

In [22]:
display(df_certificacoes)

,ID,Certificacao_1,Data_1,Certificacao_2,Data_2,Certificacao_3,Data_3
0,1,PowerBI Data Analyst Associate,29/04/2024,NaN,NaN,Azure AI Enginner Associate,18/03/2021
1,2,NaN,NaN,Azure AI Enginner Associate,12/1/2022,NaN,NaN
2,3,NaN,NaN,PowerBI Data Analyst Associate,20/09/2021,NaN,NaN
3,4,DevOps Engineer Expert,7/3/2019,Associado Desenvolvedor Azure,21/10/2015,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
75,76,NaN,NaN,NaN,NaN,NaN,NaN
76,77,NaN,NaN,PowerBI Data Analyst Associate,6/1/2025,Conceitos básicos de dados do Azure,4/9/2024
77,78,NaN,NaN,NaN,NaN,NaN,NaN
78,79,NaN,NaN,NaN,NaN,NaN,NaN
79,80,NaN,NaN,Conceitos básicos de dados do Azure,12/3/2020,PowerBI Data Analyst Associate,10/6/2024

In [ ]:
# Tabela 1
tabela1 = df_certificacoes[['idColaborador', 'Certificacao_1', 'Data_1']].dropna(subset=['Certificacao_1', 'Data_1'])
tabela1.columns = ['idColaborador', 'Certificacao', 'Data']

# Tabela 2
tabela2 = df_certificacoes[['idColaborador', 'Certificacao_2', 'Data_2']].dropna(subset=['Certificacao_2', 'Data_2'])
tabela2.columns = ['idColaborador', 'Certificacao', 'Data']

# Tabela 3
tabela3 = df_certificacoes[['idColaborador', 'Certificacao_3', 'Data_3']].dropna(subset=['Certificacao_3', 'Data_3'])
tabela3.columns = ['idColaborador', 'Certificacao', 'Data']

In [24]:
display(tabela1)

    ID                                Certificacao        Data
0    1              PowerBI Data Analyst Associate  29/04/2024
3    4                      DevOps Engineer Expert    7/3/2019
5    6              PowerBI Data Analyst Associate    7/3/2023
7    8              PowerBI Data Analyst Associate    1/8/2022
10  11  Engenheiro de Segurança Associado do Azure  16/07/2025
13  14               Cybersecurity Architec Expert    6/9/2023
15  16              PowerBI Data Analyst Associate  16/12/2021
24  25     Analista de Dados Associado de Power BI  25/01/2021
30  31              PowerBI Data Analyst Associate    2/6/2020
32  33                 Azure AI Enginner Associate  15/05/2020
40  41     Analista de Dados Associado de Power BI    8/5/2023
44  45     Analista de Dados Associado de Power BI   3/10/2022
47  48               Especialista em Administrador  26/01/2018
50  51               Especialista em Administrador  13/09/2017
56  57     Analista de Dados Associado de Power BI  17/06/2025
64  65     Analista de Dados Associado de Power BI  10/11/2020
74  75                        Administrator Expert  27/09/2023

In [25]:
display(tabela2)

    ID                                       Certificacao        Data
1    2                        Azure AI Enginner Associate   12/1/2022
2    3                     PowerBI Data Analyst Associate  20/09/2021
3    4                      Associado Desenvolvedor Azure  21/10/2015
6    7            Analista de Dados Associado de Power BI    5/2/2024
8    9                     PowerBI Data Analyst Associate  30/05/2022
13  14  Conceitos básicos de segurança, conformidade e...   10/5/2021
14  15         Engenheiro de Segurança Associado do Azure    3/4/2023
18  19            Analista de Dados Associado de Power BI  19/08/2020
21  22                        Azure AI Enginner Associate  22/08/2024
25  26                            Azure Data Fundamentals  17/01/2022
39  40                     PowerBI Data Analyst Associate  26/06/2023
57  58            Analista de Dados Associado de Power BI  14/03/2024
69  70                     PowerBI Data Analyst Associate   7/10/2021
76  77                     PowerBI Data Analyst Associate    6/1/2025
79  80                Conceitos básicos de dados do Azure   12/3/2020

In [26]:
display(tabela3)

    ID                                    Certificacao        Data
0    1                     Azure AI Enginner Associate  18/03/2021
13  14  Administrador Associado de Identidade e Acesso  25/11/2020
25  26         Analista de Dados Associado de Power BI  16/07/2025
39  40        Engenheiros de Dados Associado do Fabric  13/05/2025
43  44         Analista de Dados Associado de Power BI  15/05/2020
54  55         Analista de Dados Associado de Power BI  27/05/2020
57  58             Conceitos básicos de dados do Azure  17/01/2022
72  73         Analista de Dados Associado de Power BI    1/3/2021
76  77             Conceitos básicos de dados do Azure    4/9/2024
79  80                  PowerBI Data Analyst Associate   10/6/2024

In [27]:
tabela_final = pd.concat([tabela1, tabela2, tabela3], ignore_index=True)
display(tabela_final)

    ID                                       Certificacao        Data
0    1                     PowerBI Data Analyst Associate  29/04/2024
1    4                             DevOps Engineer Expert    7/3/2019
2    6                     PowerBI Data Analyst Associate    7/3/2023
3    8                     PowerBI Data Analyst Associate    1/8/2022
4   11         Engenheiro de Segurança Associado do Azure  16/07/2025
5   14                      Cybersecurity Architec Expert    6/9/2023
6   16                     PowerBI Data Analyst Associate  16/12/2021
7   25            Analista de Dados Associado de Power BI  25/01/2021
8   31                     PowerBI Data Analyst Associate    2/6/2020
9   33                        Azure AI Enginner Associate  15/05/2020
10  41            Analista de Dados Associado de Power BI    8/5/2023
11  45            Analista de Dados Associado de Power BI   3/10/2022
12  48                      Especialista em Administrador  26/01/2018
13  51                      Especialista em Administrador  13/09/2017
14  57            Analista de Dados Associado de Power BI  17/06/2025
15  65            Analista de Dados Associado de Power BI  10/11/2020
16  75                               Administrator Expert  27/09/2023
17   2                        Azure AI Enginner Associate   12/1/2022
18   3                     PowerBI Data Analyst Associate  20/09/2021
19   4                      Associado Desenvolvedor Azure  21/10/2015
20   7            Analista de Dados Associado de Power BI    5/2/2024
21   9                     PowerBI Data Analyst Associate  30/05/2022
22  14  Conceitos básicos de segurança, conformidade e...   10/5/2021
23  15         Engenheiro de Segurança Associado do Azure    3/4/2023
24  19            Analista de Dados Associado de Power BI  19/08/2020
25  22                        Azure AI Enginner Associate  22/08/2024
26  26                            Azure Data Fundamentals  17/01/2022
27  40                     PowerBI Data Analyst Associate  26/06/2023
28  58            Analista de Dados Associado de Power BI  14/03/2024
29  70                     PowerBI Data Analyst Associate   7/10/2021
30  77                     PowerBI Data Analyst Associate    6/1/2025
31  80                Conceitos básicos de dados do Azure   12/3/2020
32   1                        Azure AI Enginner Associate  18/03/2021
33  14     Administrador Associado de Identidade e Acesso  25/11/2020
34  26            Analista de Dados Associado de Power BI  16/07/2025
35  40           Engenheiros de Dados Associado do Fabric  13/05/2025
36  44            Analista de Dados Associado de Power BI  15/05/2020
37  55            Analista de Dados Associado de Power BI  27/05/2020
38  58                Conceitos básicos de dados do Azure  17/01/2022
39  73            Analista de Dados Associado de Power BI    1/3/2021
40  77                Conceitos básicos de dados do Azure    4/9/2024
41  80                     PowerBI Data Analyst Associate   10/6/2024

In [28]:
contagem_certificacoes = tabela_final['Certificacao'].value_counts()
print(contagem_certificacoes)

Certificacao
Analista de Dados Associado de Power BI                      12
PowerBI Data Analyst Associate                               11
Azure AI Enginner Associate                                   4
Conceitos básicos de dados do Azure                           3
Especialista em Administrador                                 2
Engenheiro de Segurança Associado do Azure                    2
Cybersecurity Architec Expert                                 1
DevOps Engineer Expert                                        1
Associado Desenvolvedor Azure                                 1
Administrator Expert                                          1
Conceitos básicos de segurança, conformidade e identidade     1
Azure Data Fundamentals                                       1
Administrador Associado de Identidade e Acesso                1
Engenheiros de Dados Associado do Fabric                      1
Name: count, dtype: int64

In [29]:
tabela_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            42 non-null     int64
 1   Certificacao  42 non-null     object
 2   Data          42 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.1+ KB

In [30]:
def limpar_e_converter(data):
    data = re.sub(r"[^0-9]+", "-", data)

    data = data.strip("-")

    return pd.to_datetime(data, dayfirst=True, errors="coerce")

tabela_final["Data"] = tabela_final["Data"].apply(limpar_e_converter)

# tabela_final["Data de Nascimento"].dt.strftime("%d-%m-%Y")

In [31]:
tabela_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            42 non-null     int64
 1   Certificacao  42 non-null     object
 2   Data          42 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 1.1+ KB

In [ ]:
# Dicionário de mapeamento (você pode ir completando com os nomes)
traducao = {
    "PowerBI Data Analyst Associate": "Analista de Dados Associado de Power BI",
    "Azure Data Fundamentals": "Conceitos básicos de dados do Azure",
    "Administrator Expert": "Especialista em Administrador",
    # adicione mais conforme necessário
}

# Criar nova coluna traduzida com base no dicionário
tabela_final["Certificacao"] = tabela_final["Certificacao"].replace(traducao)

tabela_final.head(50)

In [ ]:
#variável de ambiente para construir o caminho
caminho_base_arquivos = os.environ.get("CAMINHO_ARQUIVOS_CSV")
caminho_saida = os.path.join(caminho_base_arquivos, "dados_tratados_v2", "dc_Certificacao_tratado.csv")

# variável caminho_saida
tabela_final.to_csv(caminho_saida, index=False)

In [ ]:
#tabela_final.to_csv('../ArquivosExternos/dados_tratados_v2/dc_Certificacao_tratado.csv', index=False)